### ISSUE TITLE
Self_link not working for all fragments

### ISSUE THREAD

**Issue by lauragift21** [okkur/syna#129]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**: Not all fragments have the self_link params in the content files making it impossible to use the links directly with the URL.

**What you expected to happen**: check that all fragments have their links correctly stated in their content front matter.

**How to reproduce it (as minimally and precisely as possible)**: use the http://localhost:1313/#name-of-fragment to check if a specific fragment is linked correctly.

**Comment by stp-ip** [comment]
With this, we probably need to check each fragment and all demo data.
Maybe we should move from self_link to `anchor` or `self` or something else.
Another option would be to default to the fragment name aka reusing the filename. That would simplify the default and give the option to overwrite it via the frontmatter.

Thoughts?

**Comment by mpourismaiel** [comment]
Also since `self-link` is assigned to an elements `id` attribute and some browsers annoyingly assign that `id` to `window` (resulting in "input#someinput" being accessible via `window.someinput`) and some people using that "feature" using the filename would be more preferable since using filename would guarantee uniqueness.

**Comment by stp-ip** [comment]
Ok so the action items would be:
* default to filename as anchor
* overwritable by frontmatter variable (needs a self explanatory name)
* reduce frontmatter examples for overwriting
* document behaviour
