### ISSUE TITLE
Split out fontawesome from main.css

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#272]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Currently fontawesome is called within main.css.

**What you expected to happen**:
Split out fontawesome css into a separate file and only call it, if custom.icon_font isn't configured.
This helps with more minimal icon fonts, which improves load times.
(would also enable us to use FA pro icons on test/production pages)

**Anything else we need to know?**:
Use snake_case for custom.icon_font

**Comment by mpourismaiel** [comment]
It's possible to not separate fontawesome from main.css if the pipelines is done. We can have go templates inside the SCSS code that imports fontawsome if the config is not disabled and no icon_font is configured. That way there is no need for extra webpack entry points. What do you think?

**Comment by stp-ip** [comment]
That would be interesting. We have webpack so what's the downside to an extra webpack entry point?

**Comment by mpourismaiel** [comment]
Webpack and anything done using webpack is not configurable through config.toml. It's much easier to explain to the user that in order to change the behavior of the theme you need to change these stuff in config.toml. For example the colors are done using the config.toml variables which was impossible to do using webpack.
