### ISSUE TITLE
[nav] With sticky enabled content is not perfectly visible

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#513]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Sticky = true for nav makes the text unreadable: https://syna-demo.okkur.org/docs/global-variables/#fragment

**What you expected to happen**:
Scroll the height of the nav more, if sticky is set.

**How to reproduce it (as minimally and precisely as possible)**:
https://syna-demo.okkur.org/docs/global-variables/#fragment

**Comment by mpourismaiel** [comment]
This is a really hard problem to fix. I can't think of any working solutions. There is a solution that only work with in-page-transitions but that's not really good since most of the time the transition would be between pages.
 
Checkout react's doc that has the same problem. [reactjs.org/docs/optimizing-performance.html#brunch](https://reactjs.org/docs/optimizing-performance.html#brunch)
MDN has sort of the same problem, they have fixed it with `margin-top`. Can work but will break with custom styling: [developer.mozilla.org/en-US/docs/Web/API/Document/createElement#Examples](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement#Examples)
Kubernetes has removed the navbar in their doc page where in page transition is active
