### ISSUE TITLE
[stripe] Prevent double charges

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#522]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Currently we don't prevent double clicks and therefore double charges.

**What you expected to happen**:
Prevent accidental double charges.
Disable button, when POSTed.
Wait for response and keep disabled until data is changed again?

**Comment by mpourismaiel** [comment]
I'll fix the issue by disabling the button while the request is pending. I think removing the form after successful response is a good solution to prevent this. We can display the success message instead of the form, display error message in it's current place, disable button while pending. Let me know what you think. I'll create a WIP PR for now.

**Comment by stp-ip** [comment]
Sounds good. Maybe for a failure:
request -> disable button -> error message + form clean + button disabled for 5s?
