### ISSUE TITLE
[sidebar] Sticky navigation with split content files

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#545]
**What happened**:
We currently make sidebar navbars sticky within one content fragment.

**What you expected to happen**:
Maybe make the sidebar sticky for all content fragments?

**How to reproduce it (as minimally and precisely as possible)**:
https://about.txtdirect.org/docs/examples/ <-- multiple content files
https://about.txtdirect.org/docs/specification/ <-- one content file

**Comment by mpourismaiel** [comment]
This is a really hard problem to fix. I can't think of any working solutions. There is a solution that only work with in-page-transitions but that's not really good since most of the time the transition would be between pages.

Checkout react's doc that has the same problem. https://reactjs.org/docs/optimizing-performance.html#brunch
MDN has sort of the same problem, they have fixed it with `margin-top`. Can work but will break with custom styling: https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement#Examples
Kubernetes has removed the navbar in their doc page where in page transition is active: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#pod-v1-core
The same goes for jQuery docs: https://api.jquery.com/ajaxComplete/#entry-examples

**Comment by stp-ip** [comment]
Let me check this out a bit more. Thanks for researching this in depth. (sidenote: check-ins ;) )

**Comment by stp-ip** [comment]
Just to clarify. This is about the sidebar links being sticky only for one content file instead of for the whole page. So merging all content/docs into one content file makes the sticky sidebar work, splitting them up into multiple files, but being on the same page, only shows the sidebar navigation on the first content section and then isn't sticky anymore.
Maybe we have 2 issues here.

**Comment by mpourismaiel** [comment]
Oh I commented on the wrong issue.

**Comment by mpourismaiel** [comment]
I'm not sure how this can be fixed. We can setup something that would merge content fragments that are rendered one after the other but I don't think that's a good idea. I can't think of any other solutions to it. Do you have any ideas?

**Comment by stp-ip** [comment]
Let's document this within the user docs and we can close this. Aka recommend using a single content file, if a single sticky navigation is needed.
