### ISSUE TITLE
Use internal opengraph template

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#642]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
We currently use our own SEO templates.

**What you expected to happen**:
We could move this to internal ones from Hugo.

**Anything else we need to know?**:
Does this add value and less duplication? We have Hugo as dependency anyway.
https://gohugo.io/templates/internal/#open-graph

**Comment by mpourismaiel** [comment]
I'm not really sure about this one. We can certainly make use of the internal template for the page metadata but not images and videos since we allow for several formats of adding images to the page and I'm not sure if Hugo would catch those when making the metadata. I'm going to use this template instead of our current implementation. It would remove some code and might add more details than we currently do.
