### ISSUE TITLE
[feature] Support React 16.8+

### ISSUE THREAD

**Issue by yuri-tceretian** [okkur/syna#664]
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

**What happened**:
Theme uses quite old version of React. Do you have any plans on updating the dependencies?

**Anything else we need to know?**:
I would like to use react hooks in my components that I push to portals.

**Environment**:
- Syna Theme version:  0.15
- Hugo version:  -
- Others: -

**Comment by stp-ip** [comment]
Always happy for PRs. As the react part on our side is mostly enabling portals I think it shouldn't take much to update this to the latest version.

**Comment by mpourismaiel** [comment]
The `react-portal` fragment only adds portal so the version didn't need to be updated since React hasn't had any changes on portals in a long time. We're always happy for PRs.

**Comment by yuri-tceretian** [comment]
I was able to upgrade react without any problems, and it does not seem to break any functionality. I can create a PR.

However, when I put my component that uses hooks on a page via the portal, the component failed to start with error 
`Invalid hook call. Hooks can only be called inside the body of a function component`. 

I did some research and found that the theme's bundle had a copy of react and react-dom as well as my bundle had the copy of react. 
So I spent quite a lot of time (I am beginner in webpack world) trying different approaches and found one that worked for me. 
I made react libs to load from a CDN.
Now I have single react and reac-dom but the error is still there. 
The component is quite simple it just uses `useState` hook and does nothing else.

**Comment by mpourismaiel** [comment]
I'm sorry I totally forgot that we use react in the theme for creating the portals, and then there should be another react installed in the project for developing your components. I think a solution would be to manually link the react dependency in your project to the one in the theme. But that is not a good idea at all. We try to come up with a good solution for this. If you have any suggestions we would be more than happy to hear it.

**Comment by yuri-tceretian** [comment]
What do you think about loading 3rd party libs from external CDN. This can be automated as there are plugins for webpack that generate a JSON manifest that contains the list of dependencies with URIs pointing to a CDN. Not an expert in hugo either 😄 but I believe it is possible to update the file `js.html` in the theme to read a JSON file and generate `<script/>` tags for every record in the manifest.

**Comment by mpourismaiel** [comment]
I'm not really sure about that approach since I haven't used a cdn for loading js modules since I started using grunt so my information is really outdated. I'll create a project that works in this way and see how it functions and report back.

In the meantime if this approach works, you can:

- move "assets/js/react.js" from the theme into your own project in the same path
- remove the first line of "layouts/partials/fragments/react-portal.html"
- remove react and react-dom from theme's dependencies and build the theme assets with `yarn build-js`
- add the cdn 
- create a few components 

and see how it functions. This is not a recommended way of using Syna, just a way to both remove the other react dependency and at least make the project somewhat functioning for react. If you get the time and test this we would really appreciate it.

**Comment by yuri-tceretian** [comment]
I tried what you suggested and externalizing of react did not work. I believe that the problem is in how component `Portal` works. It does not seem to be able to load functional components. I will re-test and provide more info.

**Comment by mpourismaiel** [comment]
I think we have to remove our react support. Adding it is easy on the user side. Fixing this issue might as well be impossible. I can't figure out what to do to fix the issue. If anyone has any suggestions, please let me know.

**Comment by yuri-tceretian** [comment]
I agree that it makes sense to just remove the support. I ended up cutting it out from the theme
