### ISSUE TITLE
[item] asset.url not considered

### ISSUE THREAD

**Issue by data-henrik** [okkur/syna#701]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug 

**What happened**:
The fragment **item** can have an **asset** (image, icon). If I specify an **image**, it is displayed, including **text** for alternative text. However, the asset property **url** does not produce a clickable image.

**What you expected to happen**:
If **url** is specificed, make the image clickable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  v16.1
- Hugo version:  v62.2
- Others:

**Comment by stp-ip** [comment]
That feels like a bug. Let me check this right now.

**Comment by stp-ip** [comment]
Ok not a bug per se, but I agree this should be available.

@mpourismaiel the `items` fragment enables asset.url for images, icons etc. We should have that for all assets. Maybe create an assets helper instead of just the image helper? Not sure.
Additionally we should probably add a few tests on that front as well.

**Comment by stp-ip** [comment]
In master and next release is schedule on 2020-02-23, if you want to wait for that.
