### ISSUE TITLE
Contact form not using async

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#723]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
Previously contact form submissions for self-hosted email sending through caddy etc. was using async.

**What you expected to happen**:
Use async for form submission.

**Anything else we need to know?**:
Assumption is, that our fix for formspree impacted our self-hosted submission.

**Environment**:
- Syna Theme version: v0.16.2
- Hugo version:  v0.68.3

**Comment by stp-ip** [comment]
duplicate of #372

**Comment by stp-ip** [comment]
Partially related to #372

**Comment by Szasza** [comment]
The issue may occur due to this line: https://github.com/okkur/syna/blob/eb206a014b7f52a96a78e0914be7d8b74d4f7389/layouts/partials/fragments/contact.html#L24

If the email is set in the config, the `data-has-formspree` will always be present and will be true.

As a test, I have modified the line to `{{- if and (in .Params.post_url "formspree.io") (isset .Params "email") -}}` and the form was submitted via AJAX as expected.
