### ISSUE TITLE
Change color of nav links and copyright info

### ISSUE THREAD

**Issue by solrayc** [okkur/syna#727]
I'd like to change the color of nav and footer link text color.
Current color choice is very low contrast.

It looks like the color is automatically determined by the background color.
What is the best way to change nav and footer link text color for this theme?

**Comment by mpourismaiel** [comment]
The best way is to add custom styling.

The built-in fragments follow the bootstrap theme with our custom color pallette and text color, as you mentioned, is determined by background color of the fragment. To circumvent this you can add your own stylesheet and change the colors specifically for the fragment. Each fragment has an id, the same as it's filename.

In this situation adding stylesheet is the better solution since the change is small and you can still receive updates on the fragment and your styles wouldn't break in the future.

Chwck out our [documentation](https://about.okkur.org/syna/docs/development/) on styles and adding custom stylesheet.

**Comment by stp-ip** [comment]
There is also a way to generally use different colors. Take a look here: https://about.okkur.org/syna/docs/supported-colors/

**Comment by JOduMonT** [comment]
> There is also a way to generally use different colors. Take a look here: https://about.okkur.org/syna/docs/supported-colors/

related to this, I change my colors scheme and now secondary is dark so had to [superseed this file](https://github.com/okkur/syna/blob/master/layouts/partials/helpers/text-color.html#L4) to remove secondary from this line. @stp-ip it is a better way you would recommend to manage this situation ?

**Comment by stp-ip** [comment]
Can't think of a better way. Staying close to the color contrast as bootstrap helps. Switching say light with dark, will unfortunately break a few default things.
Most colors should use the text-color helper so overwriting that as well should be ok.
Happy to discuss better solutions in a separate issue.
