### ISSUE TITLE
Items get resized wrong

### ISSUE THREAD

**Issue by IvanTurgenev** [okkur/syna#775]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug 

**What happened**:
Image get resized wrongly
**What you expected to happen**:
Image get resized and centered correctly
**How to reproduce it (as minimally and precisely as possible)**:
use items, create an image with 300x110 ratio, a perfectly centered png, gets shifted because bad resizing
**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  0.17.1
- Hugo version:  v0.70.0/extended darwin/amd64

includes generated images and fragment md
[bug.zip](https://github.com/okkur/syna/files/4705076/bug.zip)

- Others:

**Comment by mpourismaiel** [comment]
We resize the image using Hugo. The line responsible for this is:

/layouts/partials/helpers/image.html:44
```
{{- .root.page_scratch.Set "resource" ((.root.page_scratch.Get "resource").Fill .resize) -}}
```

Which is called by:

/layouts/partials/fragments/items.html:28
```
<img src="{{ partial "helpers/image.html" (dict "root" $self "this" $this "asset" . "resize" "300x110") }}" class="p-2 w-75 mb-2" alt="{{ .text | default $item.title }}">
```

Since Syna is a theme within the bounds of Hugo, we have to rely on Hugo to perform functionalities that rely on third party software or anything in general that requires other libraries that are not available within the build system which is Hugo.

I suggest reporting the issue to Hugo as we're unable to fix the issue within Syna.
