### ISSUE TITLE
Syna starter repo in documentation redirects to https://about.txtdirect.org/

### ISSUE THREAD

**Issue by RescueRangers** [okkur/syna#852]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug

**What happened**:
When clicking syna starter repo in documentation I am being redirected to https://about.txtdirect.org/
**What you expected to happen**:
Getting a syna starter repo
**How to reproduce it (as minimally and precisely as possible)**:
Scroll down to Using Syna section in documentation and click on the link at the end of the second line.
**Anything else we need to know?**:

**Environment**:
- Syna Theme version:  
- Hugo version:  
- Others:

**Comment by robbm1** [comment]
This also happens when clicking on the **Homepage** button at https://themes.gohugo.io/syna/:
![image](https://user-images.githubusercontent.com/35958943/115400670-dbae0980-a1e9-11eb-9d74-574f14a5ca28.png)

**Comment by stp-ip** [comment]
Thanks for reporting both issues. Seems like something went haywire with our redirection records. Will check this out and fix.
Will report back once it's deployed.

**Comment by stp-ip** [comment]
This should be fixed. txtd.io, which we use for our git based redirects had a single instance throwing DNS errors due to an upstream blocked IP. Therefore most of the traffic should have been unaffected, but this single instance did fallback to the default redirect, which happens to be the underlying open source project's website.
